### ISSUE TITLE
不能正常向QQ群里发送文字消息

### ISSUE THREAD

**Issue by Under-estimate** [ViosinDeng/HamsterBot-IOTQQ#2]
发送的JSON：
```json
{"toUser":757360354,"sendToType":2,"sendMsgType":"TextMsg","content":"测试","groupid":0,"atUser":0,"replayInfo":null}
```
返回的JSON：
```json
{"Msg":"","Ret":0}
```

在QQ群里未收到发送的消息。

---
经过测试，当content中的字符串为1~2个非中文字符时，发送的消息可以在QQ群里收到。
如果发送大于2个非中文字符或者发送中文字符，QQ群里就不能收到发送的消息了。

**Comment by MiniDay** [comment]
我这里测试正常，你确定你的IOTQQ更新了吗？（好像之前的版本有这个问题

**Comment by Under-estimate** [comment]
IOTQQ版本:`iotbot_3.0.1_windows_amd64`
操作系统:`Windows10 x64`
JDK版本:`1.8.0_131`

**Comment by MiniDay** [comment]
再次测试依然没有问题，也许你该试试重新登录IOTBOT？

**Comment by Under-estimate** [comment]
发送消息时在IOTBot的后台可以看到IOT已经接收到了请求，但是QQ群里还是不会显示。
我试着用Chorme的API测试扩展直接向IOT发送请求，但还是不成功。

我询问了IOTBot的作者，他的回答是：我的这个QQ账号可能**被屏蔽了**。

在我退出登录之后，我尝试再次登录，但是尝试了很多次之后仍然不能成功登录IOTBot，可能这个账号真的是被屏蔽了吧。

根据IOTBot作者的回答，屏蔽原因可能是之前我尝试通过刷新keys解决这个问题，而**频繁刷新可能会导致被屏蔽**。

总之，现在看来这个问题的原因应该不在这个项目之中。

**Comment by MiniDay** [comment]
那么你也许可以试试，更换一个新的github账号并获取新的gitter API，然后再重新初始化iotbot。
以及，这个屏蔽似乎不会持续很久，我在刚起步这个项目时也曾遇到过QQ群无法发送文字消息的bug，但是过两天之后又恢复了。这样是我起初询问`你确定你的IOTQQ更新了吗？`的原因。
